### ISSUE TITLE
Fix corrupted links in the documentation

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/doc-starter-myfirstsite#1]
@anatol-sialitski commented on [Thu Aug 15 2019](https://github.com/enonic/doc-xp/issues/74)

Details https://docs.google.com/spreadsheets/d/1p4x_W5JXqduCnZoR_siNzdJMKhaR5IqyE06W3orIOqI/edit?usp=sharing

**Comment by jsi** [comment]
Done in PR#2
